Fetching release version works
TODO: Compilation of master fails due to SUSE repo issue

diff --git a/e2e/start b/e2e/start
--- a/e2e/start
+++ b/e2e/start
@@ -290,40 +290,37 @@ EOF
 }
 
 function install-telemetry-server() {
-  if [ -z "$1" ]; then
-    echo >&2 "error: install-telemetry-server: argument missing: need 1, have $#"
+  set -x
+
+  if [[ -z "${TELEMETRY_IMAGE}" ]]; then
+    echo >&2 "error: TELEMETRY_IMAGE is not set"
     return 1
   fi
-  if [[ "$1" != "stable" && "$1" != "dev" && "$1" != "master" ]]; then
-    echo >&2 "error: install-telemetry-server: argument invalid: need stable, dev, or master, have $1"
-    return 1
-  fi
+
+  yq eval ".spec.template.spec.containers[0].image = \"${TELEMETRY_IMAGE}\"" \
+    manifests/telemetry-server/deployment.yaml -i
+
   kubectl \
     -n telemetry \
     apply \
-    -k ./manifests/telemetry-server/$1
+    -k ./manifests/telemetry-server
 }
 
 function install-telemetry-client() {
-  if [ -z "$1" ]; then
-    echo >&2 "error: install-telemetry-client: argument missing: need 1, have $#"
-    return 1
-  fi
-  if [[ "$1" != "stable" && "$1" != "dev" && "$1" != "master" ]]; then
-    echo >&2 "error: install-telemetry-client: argument invalid: need stable, dev, or master, have $1"
-    return 1
-  fi
-  kubectl \
-    -n telemetry \
-    apply \
-    -k ./manifests/telemetry-client/$1
-}
+  set -x
 
-function install-telemetry-client-dev() {
+  if [[ -z "${TELEMETRY_IMAGE}" ]]; then
+    echo >&2 "error: TELEMETRY_IMAGE is not set"
+    return 1
+  fi
+
+  yq eval ".spec.template.spec.containers[0].image = \"${TELEMETRY_IMAGE}\"" \
+    manifests/telemetry-client/deployment.yaml -i
+
   kubectl \
     -n telemetry \
     apply \
-    -k ./manifests/telemetry-client/dev
+    -k ./manifests/telemetry-client
 }
 
 function install-base() {
